name: CI & CD
on:
    push:
        branches:
            - hexo
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive
                  lfs: true
            - name: Use Node.js
              uses: actions/setup-node@v2-beta
              with:
                  node-version: 14
                  cache: yarn
            - name: Install & build
              run: yarn  &&  yarn build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./public
                  cname: kaiyuanshe.cn
                  publish_branch: master
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true
